version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: db_microservico
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservico
    ports:
      - "3307:3306"

  microservico:
    build: .
    container_name: microservico_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL = jdbc:mysql://mysql:3306/microservico?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME = root
      - SPRING_DATASOURCE_PASSWORD = root